name=DisplayLib
version=1.0.0
author=Leon-UdrugaMIS
maintainer=Leon-UdrugaMIS
sentence=Library for 4-digit 7-segment displays (common anode/cathode).
paragraph=Supports integer, float, text and degree symbol rendering with multiplex refresh.
category=Display
architectures=*
